### ISSUE TITLE
Can't open Burnr light-client in-browser wallet example

### ISSUE THREAD

**Issue by juandesouza** [paritytech/substrate-connect#1455] opened 2023-07-08 00:52 UTC
I tried to open the Burnr light-client in-browser wallet example from the Substrate Connect from substrate docs, and it didn't open on both Brave and Firefox. I'm using last version of MX Linux, and the browsers are updated. I have installed Substrate connect browser extension on both browsers and restarted the computer before trying.

On the Firefox console appears the error message:
2023-07-07 12:27:53    BURNR-WALLET: Error: CrashError: Error while creating the chain: CompileError: wasm validation error: at offset 16960: unrecognized opcode: fd 0
    Wrapper main.js:152690
    _createSuperInternal main.js:152687
    CrashError types.ts:141
    ../../packages/connect/dist/mjs/connector/extension.js/createScClient/_callee/_callee$/< extension.ts:97
    js

And on Brave console appears the message:
logger.js:56 2023-07-07 12:16:02    BURNR-WALLET: Error: CrashError: Error while creating the chain: CompileError: WebAssembly.compile(): Compiling function #22 failed: Wasm SIMD unsupported @+16960
    at extension.ts:97:24
    at extension.ts:22:34

**Comment by wirednkod** [comment] 2023-07-10 09:25
Thank you for reporting this @juandesouza 

I have not seen this error before, and cannot reproduce. I will investigate further more and get back to you

**Comment by wirednkod** [comment] 2023-07-10 18:36
@juandesouza I have updated the extension to version 0.2.8. Can you please verify that you have that version and you can use Burnr wallet normally - without the error above appear?

**Comment by juandesouza** [comment] 2023-07-11 18:10
I'm using the 0.2.8 version. I'm still trying on both browsers and it still doesn't open. I recorded the screen, so you can see: https://youtu.be/r6BwxV6zmQ0

**Comment by wirednkod** [comment] 2023-07-12 09:20
@juandesouza I already opened an issue to [Smoldot repo](https://github.com/smol-dot/smoldot/issues/895). 

Can you please verify that smoldot initiating is on version 1.0.11 and try to run the wallet without the extension installed? If this fails as well, can you run the same test on an incognito window without any extensions active?

I apologize in advance for asking for all these tests, but I am not able to reproduce the error in any browser on Ubuntu linux or MacOs

**Comment by juandesouza** [comment] 2023-07-12 13:44
I update linux every day. Updates of brave and firefox come automatically from the linux package manager.
Brave: [Version 1.52.130 Chromium: 114.0.5735.198 (Build officiel) (64 bits)](https://brave.com/latest/)
Firefox: 115.0.1 (64-bit)

**Comment by wirednkod** [comment] 2023-07-12 13:57
Thank you @juandesouza for the response.
This is very strange as I have on m Ubuntu the same versions (64-bits as well) and I cannot replicate the error. I will try to investigate some more, and provide your response to smoldot team and get back to you

**Comment by wirednkod** [comment] 2023-07-12 17:20
Following @tomaka 's suggestions, it seems like SIMD is disabled for your browsers. can you check the comment of Pierre, https://github.com/smol-dot/smoldot/issues/895#issuecomment-1632600109 and try to check if your browsers supports it (there is even a way to check that: https://github.com/GoogleChromeLabs/wasm-feature-detect )

**Comment by wirednkod** [comment] 2023-07-12 20:04
Based on this comment https://github.com/smol-dot/smoldot/issues/895#issuecomment-1633118029 this is an environment issue rather that a substrate connect or smoldot issue, thus I will close the issue here. Please feel free to add any info in case you find a related solution

**Closed by wirednkod** 2023-07-12 20:04 UTC

**Comment by juandesouza** [comment] 2023-07-12 21:27
I'm going to add one more information that could be useful for you. When I was trying to install Substrate, I received an error message saying that Rust wasm was not installed. Since I didn't know what was the correct package that I should install, I installed everything that I found with "rust" and "wasm" in their names, so I ended up installed a lot of crap that I didn't need. Now that I'm receiving an error on Substrate connect that is related to wasm, it makes me think if I have installed something that could be causing some problem. That packages that I have installed now with rust and wasm in their names are:
librust-object+parity-wasm-dev/oldstable,now 0.12.0-4 amd64  [installé]
librust-object+wasm-dev/oldstable,now 0.12.0-4 amd64  [installé]
librust-parity-wasm-dev/oldstable,now 0.41.0-1 amd64  [installé]
librust-rand+wasm-bindgen-dev/oldstable,now 0.7.3-3 amd64  [installé]
librust-rand-os+wasm-bindgen-dev/oldstable,now 0.2.2-2 amd64  [installé]
librust-uuid+wasm-bindgen-dev/oldstable,now 0.8.1-3 amd64  [installé]
librust-wasm-bindgen+default-dev/oldstable,now 0.2.58-1 amd64  [installé]
librust-wasm-bindgen+serde-dev/oldstable,now 0.2.58-1 amd64  [installé]
librust-wasm-bindgen+serde-json-dev/oldstable,now 0.2.58-1 amd64  [installé]
librust-wasm-bindgen+serde-serialize-dev/oldstable,now 0.2.58-1 amd64  [installé]
librust-wasm-bindgen+spans-dev/oldstable,now 0.2.58-1 amd64  [installé]
librust-wasm-bindgen+strict-macro-dev/oldstable,now 0.2.58-1 amd64  [installé]
librust-wasm-bindgen+xxx-debug-only-print-generated-code-dev/oldstable,now 0.2.58-1 amd64  [installé]
librust-wasm-bindgen-backend+extra-traits-dev/oldstable,now 0.2.58-1 amd64  [installé]
librust-wasm-bindgen-backend-dev/oldstable,now 0.2.58-1 amd64  [installé]
librust-wasm-bindgen-dev/oldstable,now 0.2.58-1 amd64  [installé]
librust-wasm-bindgen-macro+spans-dev/oldstable,now 0.2.58-1 amd64  [installé]
librust-wasm-bindgen-macro+strict-macro-dev/oldstable,now 0.2.58-1 amd64  [installé]
librust-wasm-bindgen-macro-dev/oldstable,now 0.2.58-1 amd64  [installé]
librust-wasm-bindgen-macro-support+extra-traits-dev/oldstable,now 0.2.58-2 amd64  [installé]
librust-wasm-bindgen-macro-support+spans-dev/oldstable,now 0.2.58-2 amd64  [installé]
librust-wasm-bindgen-macro-support-dev/oldstable,now 0.2.58-2 amd64  [installé]
librust-wasm-bindgen-shared-dev/oldstable,now 0.2.58-1 amd64  [installé]
librust-wasm-bindgen-webidl-dev/oldstable,now 0.2.58-1 amd64  [installé]
libstd-rust-dev-wasm32/oldstable,oldstable,now 1.48.0+dfsg1-2 all  [installé]

Could any of these packages be causing the problem?

**Comment by wirednkod** [comment] 2023-07-13 00:54
The messages you receive are mentioning that  SIMD is disabled in the browsers, so I would definitely look in that direction. I am not sure (but ive never heard of) extra wasm packages disabling it for the browser though.

**Comment by juandesouza** [comment] 2023-07-13 20:27
I removed from my computer all the packages with the name "wasm" in it, restarted the computer, and then.... it still didn't work! It's unbelievable that even on my cellphone it works...
Unfortunately I'll have to say that I give up. It's easier to reinstall the OS or even buy another computer.
Thank you very much for your attention and help.

**Comment by wirednkod** [comment] 2023-07-13 20:36
Im sorry to hear that @juandesouza . I wish there was a solution for this but it is really rare.
Thank you for bringing it to our attention nevertheless
