### ISSUE TITLE
Issue connecting to Interlay-parachain

### ISSUE THREAD

**Issue by wirednkod** [paritytech/substrate-connect#927] opened 2022-04-05 09:30 UTC
Below can be found the [logs](https://github.com/paritytech/substrate-connect/files/8416776/rococo-local-testnet-No_peers.txt), [relay](https://github.com/paritytech/substrate-connect/files/8416793/rococo-local-0.9.16.txt) and [parachain](https://github.com/paritytech/substrate-connect/files/8416796/staging-latest-parachain-1.7.4.txt) specs.

When trying to connect there is always `Peers: 0` and `synching: true`

cc @tomaka

**Comment by wirednkod** [comment] 2022-04-05 10:19
[more logs with smoldot 0.6.12](https://github.com/paritytech/substrate-connect/files/8417167/more-logs-0.6.12.txt)

**Comment by tomaka** [comment] 2022-04-05 10:58
> Below can be found the [logs](https://github.com/paritytech/substrate-connect/files/8416776/rococo-local-testnet-No_peers.txt), [relay](https://github.com/paritytech/substrate-connect/files/8416793/rococo-local-0.9.16.txt) and [parachain](https://github.com/paritytech/substrate-connect/files/8416796/staging-latest-parachain-1.7.4.txt) specs.

This set of logs indicate that the relay chain is busy doing the warp sync.
The parachain is stuck because it's waiting for the relay chain to be idle.

> [more logs with smoldot 0.6.12](https://github.com/paritytech/substrate-connect/files/8417167/more-logs-0.6.12.txt)

Haven't looked yet

**Comment by tomaka** [comment] 2022-04-05 11:09
> [more logs with smoldot 0.6.12](https://github.com/paritytech/substrate-connect/files/8417167/more-logs-0.6.12.txt)

Here the error is clear:

> 13:17:56 338 Debug - sync-service-staging_testnet ParaheadFetchOperations => Error(relay_blocks=0x67ee…fc1b, error=NoCore)

**Comment by wirednkod** [comment] 2022-04-22 13:44
We can continue with the integration if requested - all we just need an up to date checkpoint of the chain.
The problem with Interlay chain is that their epoch duration is way too short, with the consequence is that it takes ages to sync
But if we have an up to date checkpoint then we can bypass the issue

**Comment by tomaka** [comment] 2022-10-12 11:38
There's no actionable item here. Everything works as intended. Closing.

**Closed by tomaka** 2022-10-12 11:38 UTC
