### ISSUE TITLE
The extension gets "stuck" in the past

### ISSUE THREAD

**Issue by josepot** [paritytech/substrate-connect#1786] opened 2024-01-23 09:40 UTC
### Issue Description

After a period of inactivity, then the extension stops announcing new blocks and nothing seems to work until you manually reset it.

![image](https://github.com/paritytech/substrate-connect/assets/8620144/f9ed1085-2649-4d16-b676-f1550214cc19)

### Steps to reproduce the issue

Steps to reproduce the issue
1. Use the extension in a DApp
2. Put your laptop to sleep for a few minutes
3. Try using the extension again

### Describe the results you received

The extension stops working, no new blocks get announced and the DApps can't communicate with smoldot

### Describe the results you expected

I expected for that not to happen

### Substrate-Connect version

extension: 0.3.1 npm-package: 0.8.5

### Provider

Chrome

### Browser version

As I laready mentioned before: 0.3.1

### Additional environment details

(This issue template is a huge PITA)

### Additional information

Additional information like issue happens only occasionally or issue happens with a particular architecture or on a particular setting

**Comment by ryanleecode** [comment] 2024-03-06 22:39
im able to further reproduce with the following ..

1. load the demo app
2. connect to a vpn (breaks ur current internet connect)
3. reload the demo app

the app will nuke with smoldot panicing

```
{code: -32603, message: 'Error: panicked at /__w/smoldot/smoldot/light-base…5:35:\ncalled `Option::unwrap()` on a `None` value'}
code
: 
-32603
message
: 
"Error: panicked at /__w/smoldot/smoldot/light-base/src/runtime_service.rs:1845:35:\ncalled `Option::unwrap()` on a `None` value"
[[Prototype]]
: 
Object
```

**Comment by ryanleecode** [comment] 2024-03-07 20:08
marking as blocked for now

https://github.com/smol-dot/smoldot/issues/1712

**Comment by ryanleecode** [comment] 2024-03-13 18:10
I haven't crashed or froze since the latest update. Will close this for now. Plz re-open if it happens again.

**Comment by ryanleecode** [comment] 2024-03-22 22:34
nope still goes to sleep. reopened

**Comment by josepot** [comment] 2024-04-29 16:25
According to the comment on #2151 :

> This doesn't fix https://github.com/paritytech/substrate-connect/issues/1786 but reduces the likelihood of the extension getting stuck in the past

it seems that this issue was closed by accident.

**Comment by ryanleecode** [comment] 2024-04-29 17:16
> According to the comment on #2151 :
> 
> > This doesn't fix https://github.com/paritytech/substrate-connect/issues/1786 but reduces the likelihood of the extension getting stuck in the past
> 
> it seems that this issue was closed by accident.

Yah github autoclosed it or something

**Comment by ryanleecode** [comment] 2024-04-29 17:47
For visibility purposes, since most of the discussion took place in element, we are going to find a solution that restarts smoldot if it ever gets stucks. 

To determine if it is stuck we will check if smoldot immediately responds to a __follow event__ with a __subscription id__

**Closed** 2024-05-22 13:16 UTC

**Comment by ryanleecode** [comment] 2024-05-24 15:54
Fixed in https://github.com/paritytech/substrate-connect/commit/21b47e2d17f1b6a6749b4029ac49f4c07514bc51
