### ISSUE TITLE
App unresponsive after Substrate Connect connects

### ISSUE THREAD

**Issue by rossbulat** [paritytech/substrate-connect#1370] opened 2023-01-03 11:43 UTC
Related to https://github.com/paritytech/polkadot-staking-dashboard/issues/529

The staking dashboard becomes unresponsive after Substrate Connect successfully connects to the network.

Browser: Chrome 108.0.5359.124
@polkadot/rpc-provider: 9.10.5

To test, fetch the [`rb-enable-substrate-connect`](https://github.com/paritytech/polkadot-staking-dashboard/pull/528) branch and run the app locally. Switch to the light client from the Networks modal. After a couple of seconds of connecting the app will rapidly get slower until it stops responding.

This behaviour could suggest a memory issue.

**Comment by wirednkod** [comment] 2023-01-03 15:06
I have tried the branch you mention, and it seems to me that the issue is due to the nomination screen mainly. It seems to be the same issue as before (too much delay on returning nomination list). In addition the only part that I realized a delay and eventual freeze of the app was when navigating from page to page. TBH, my first impression is that this is due to the way that react calls light client (multiple times on same request due to rerenders) rather than an issue of substrate-connect. I will though keep checking it. Thank you for reporting it

**Comment by rossbulat** [comment] 2023-01-15 06:45
To clarify some points:
- the app freezes regardless of what pages you visit. Even if you do not visit any pages and just wait, the freeze still takes place.
- the light client is only instantiated once, regardless of re-renders.
- it is not clear to me which calls (if any) are causing the freeze.

**Comment by wirednkod** [comment] 2023-03-27 15:19
Hey @rossbulat - I think this is resolved since Substrate connect integrated v1.0.
 I will close this for now - please reopen, in case this is identified again;

**Closed by wirednkod** 2023-03-27 15:19 UTC
